## A little area for some numpy

In [16]:
import numpy as np

CURVE_CENTER = 80

grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):

    average = grades.mean()
    print(average)

    change = CURVE_CENTER - average
    print(CURVE_CENTER)
    print(change)

    new_grades = grades + change
    print(new_grades)

    return np.clip(new_grades, grades, 100)


curve(grades)

60.75
80
19.25
[ 91.25  54.25  83.25 107.25  70.25 109.25  93.25  31.25]


array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

### arrays

In [17]:
temperatures = np.array([29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
12.6, 49.9, 38.6, 31.3, 9.2, 22.2
 ]).reshape(2, 2, 3)

In [18]:
temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [19]:
temperatures.shape

(2, 2, 3)

In [20]:
np.swapaxes(temperatures, 1,2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

## more axis

In [21]:
table = np.array([
        [5, 3, 7, 1],
        [2, 6, 7 ,9],
        [1, 1, 1, 1],
       [4, 3, 2, 0],
   ])

## Gives the max value in the table (Axis 0 is vertical, axis 1 is horizontal)

In [22]:
table.max()

9

In [23]:
table.max(axis=0)

array([5, 6, 7, 9])

In [24]:
table.max(axis=1)

array([7, 9, 1, 4])

In [25]:
table.min(axis = 0)

array([1, 1, 1, 0])

In [26]:
table.mean(axis=0)

array([3.  , 3.25, 4.25, 2.75])

## Planes


In [36]:
A = np.arange(6).reshape(2, 1, 3)
A

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [46]:
B = np.arange(18).reshape(2, 3, 3)
B

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [47]:
A+B

array([[[ 0,  2,  4],
        [ 3,  5,  7],
        [ 6,  8, 10]],

       [[12, 14, 16],
        [15, 17, 19],
        [18, 20, 22]]])

### the above needs more understanding

In [59]:
square = np.array([
   ...:     [16, 3, 2, 13],
   ...:     [5, 10, 11, 8],
   ...:     [9, 6, 7, 12],
   ...:     [4, 15, 14, 1]
   ...: ])

In [60]:
for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum() == 34
    

In [55]:
assert square[:2, :2].sum() == 34

In [56]:
assert square[2:, :2].sum() == 34

In [57]:
assert square[:2, 2:].sum() == 34

In [61]:
assert square[2:, 2:].sum() == 34

### handy use of the assert comment, changes a number an those concerned in the area gave and assertion error

## Masking

In [76]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(3,8)

In [77]:
numbers

array([[ 5,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46, 48, 50]])

In [78]:
mask = numbers % 4 == 0

In [79]:
mask

array([[False, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True, False]])

In [80]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

## Shorthand version

In [69]:
by_four = numbers[numbers % 4 ==0]
by_four

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [81]:
from numpy.random import default_rng

In [82]:
rng = default_rng()

In [84]:
values = rng.standard_normal(10000)

In [85]:
values[:5]

array([ 0.94124173, -1.04345598, -0.48719889, -0.31549914,  0.57212761])

In [86]:
std = values.std()

In [87]:
std

0.9943215762084805

In [88]:
filtered = values[(values > -2 * std) & (values < 2 * std)]

In [89]:
filtered.size

9548

In [90]:
values.size

10000

In [91]:
filtered.size/values.size

0.9548

In [108]:
import matplotlib.image as mpimg

img = mpimg.imread("image.jpg")

print(type(img))

print(img.shape)

<class 'numpy.ndarray'>
(2322, 4128, 3)


In [114]:
output = img.copy()

output[:, :, :1] = 0

mpimg.imsave("blue.jpg", output)

In [116]:
averages = img.mean(axis=2)  # Take the average of each R, G, and B

mpimg.imsave("bad-gray.jpg", averages, cmap="gray")